models:
  openrouter:
    enabled: true
    api_key_env: OPENROUTER_API_KEY
    models:
      - name: "openai/gpt-4-turbo"
        display_name: "GPT-4 Turbo"
        provider: "openai"
        cost_per_1k_input: 0.01
        cost_per_1k_output: 0.03
        description: "Fast and capable GPT-4 model"
      
      - name: "openai/gpt-4"
        display_name: "GPT-4"
        provider: "openai"
        cost_per_1k_input: 0.03
        cost_per_1k_output: 0.06
        description: "Most capable GPT-4 model"
      
      - name: "anthropic/claude-3.5-sonnet"
        display_name: "Claude 3.5 Sonnet"
        provider: "anthropic"
        cost_per_1k_input: 0.003
        cost_per_1k_output: 0.015
        description: "Balanced Claude model, great for writing"
      
      - name: "anthropic/claude-3-opus"
        display_name: "Claude 3 Opus"
        provider: "anthropic"
        cost_per_1k_input: 0.015
        cost_per_1k_output: 0.075
        description: "Most capable Claude model"
      
      - name: "meta-llama/llama-3-70b-instruct"
        display_name: "Llama 3 70B"
        provider: "openrouter"
        cost_per_1k_input: 0.00059
        cost_per_1k_output: 0.00079
        description: "High-quality open-source model, very cost-effective"
      
      - name: "meta-llama/llama-3-8b-instruct"
        display_name: "Llama 3 8B"
        provider: "openrouter"
        cost_per_1k_input: 0.00005
        cost_per_1k_output: 0.00005
        description: "Fast and cheap, good for drafts"

  direct:
    openai:
      enabled: true
      api_key_env: OPENAI_API_KEY
      models:
        - name: "gpt-4-turbo-preview"
          display_name: "GPT-4 Turbo (Direct)"
          cost_per_1k_input: 0.01
          cost_per_1k_output: 0.03
        
        - name: "gpt-4"
          display_name: "GPT-4 (Direct)"
          cost_per_1k_input: 0.03
          cost_per_1k_output: 0.06
        
        - name: "gpt-3.5-turbo"
          display_name: "GPT-3.5 Turbo (Direct)"
          cost_per_1k_input: 0.0005
          cost_per_1k_output: 0.0015
    
    anthropic:
      enabled: true
      api_key_env: ANTHROPIC_API_KEY
      models:
        - name: "claude-3-5-sonnet-20241022"
          display_name: "Claude 3.5 Sonnet (Direct)"
          cost_per_1k_input: 0.003
          cost_per_1k_output: 0.015
        
        - name: "claude-3-opus-20240229"
          display_name: "Claude 3 Opus (Direct)"
          cost_per_1k_input: 0.015
          cost_per_1k_output: 0.075
        
        - name: "claude-3-sonnet-20240229"
          display_name: "Claude 3 Sonnet (Direct)"
          cost_per_1k_input: 0.003
          cost_per_1k_output: 0.015

